### ISSUE TITLE
Tweak the docs sidebar so that the background for active items extend all the way

### ISSUE THREAD

**Issue by caendesilva** [hydephp/hydefront#47]
Current:

![image](https://user-images.githubusercontent.com/95144705/167690246-598ab136-1650-4546-aa70-79ed94abeaf6.png)

![image](https://user-images.githubusercontent.com/95144705/167690379-b51e8877-1950-434b-9740-6df60686abe0.png)

Acheived by changing 

```css
#lagrafo-app #sidebar #sidebar-navigation .sidebar-navigation-item {
    margin-left: -1rem;
    padding-left: 1rem;
}
```

to

```css
#lagrafo-app #sidebar #sidebar-navigation .sidebar-navigation-item {
    margin-left: -1rem;
    padding-left: 1rem;
    margin-right: -1rem;
    padding-right: 1rem;
}
```
